# Data Scaling

Scaling Techniques:
- Min-Max Scaling (Normalization)
- Standardization (Z-Score Normalization)
- Robust Scaling

### Upload Needed Libraries

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

### Sample Data

In [2]:
data_np = np.array([[1.0, 200.0, 3.0],
                    [2.0, 300.0, 6.0],
                    [3.0, 400.0, 9.0],
                    [4.0, 500.0, 12.0],
                    [5.0, 600.0, 15.0]])

### #1 Min-Max Scaling (Normalization)

In [3]:
min_max_scaler = MinMaxScaler()
data_min_max_scaled = min_max_scaler.fit_transform(data_np)

In [4]:
print("Original Data:\n", data_np)
print("\nMin-Max Scaled Data:\n", data_min_max_scaled)

Original Data:
 [[  1. 200.   3.]
 [  2. 300.   6.]
 [  3. 400.   9.]
 [  4. 500.  12.]
 [  5. 600.  15.]]

Min-Max Scaled Data:
 [[0.   0.   0.  ]
 [0.25 0.25 0.25]
 [0.5  0.5  0.5 ]
 [0.75 0.75 0.75]
 [1.   1.   1.  ]]


### #2 Standardization (Z-Score Normalization)

In [5]:
standard_scaler = StandardScaler()
data_standardized = standard_scaler.fit_transform(data_np)

In [6]:
print("Original Data:\n", data_np)
print("\nStandardized Data (Z-score):\n", data_standardized)

Original Data:
 [[  1. 200.   3.]
 [  2. 300.   6.]
 [  3. 400.   9.]
 [  4. 500.  12.]
 [  5. 600.  15.]]

Standardized Data (Z-score):
 [[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


### #3 Robust Scaler

In [7]:
robust_scaler = RobustScaler()                               
data_robust_scaled = robust_scaler.fit_transform(data_np)


In [8]:
print("Original Data:\n", data_np)
print("\nRobust Scaled Data:\n", data_robust_scaled)

Original Data:
 [[  1. 200.   3.]
 [  2. 300.   6.]
 [  3. 400.   9.]
 [  4. 500.  12.]
 [  5. 600.  15.]]

Robust Scaled Data:
 [[-1.  -1.  -1. ]
 [-0.5 -0.5 -0.5]
 [ 0.   0.   0. ]
 [ 0.5  0.5  0.5]
 [ 1.   1.   1. ]]
